{
    "narratorbot": "Narrator Bot",
    "ping": "Ping",
    "boosterDaily": "क्योंकि आप एक बूस्टर हैं, आपको सामान्य पुरस्कार राशि से दोगुना प्राप्त हुआ है!",
    "daily": "{{emoji}} बढ़िया!  आपको {{number}} {{prize}} मिल गया है!",
    "noItemProvided": "कृपया खरीदने के लिए दुकान से एक वस्तु निर्दिष्ट करें !",
    "unknownColor": "क्षमा करें, मैं {{color}} रंग को नहीं पहचानता।  सुनिश्चित करें कि आपने \\`+shop colors\\` में से एक उचित रंग चुना है!",
    "alreadyPurchasedRole": "अरे, आपने वह भूमिका पहले ही खरीद लिया है!",
    "alreadyPurchasedColor": "अरे, आपने वह रंग पहले ही खरीद लिया है!",
    "alreadyPurchasedItem": "अरे, आपने वह {{item}} पहले ही खरीद लिया है!",
    "notEnoughCurrency": "क्षमा करें, आपके पास इसके लिए पर्याप्त {{currency}} नहीं है!",
    "channelPurchaseSuccess": "आपने एक निजी चैनल खरीदा है! आप यहां अपना चैनल संपादित कर सकते हैं: {{channelLink}}",
    "bugNoArguments": "Please describe the bug properly.\nMention details of how the bug has occurred, for which role and in which game. Do mention details of expected and observed results.\nIf you have any screenshots to add, create a bug with above mentioned details. Then go to the URL generated and add your screenshots in the comments of the issue.",
    "bugNoGameServer": "Images attached to a bug from the game server cannot be submitted! Please use the link below to add your attachments.",
    "bugSuccess": "The bug has successfully been reported! Please provide any screenshots or more information here:\n{{url}}",
    "suggestNoArguments": "Please describe the suggestion properly.\nMention details of how you want to improve current system / how your idea is effective and needs to be added in WOVSIM. Do mention the difference in current system and your idea if applicable.\nIf you have any screenshots / details to add, create an issue with above mentioned details. Then go to the URL generated and add your them in the comments of the suggestion.",
    "suggestNoGameServer": "Images attached to a suggestion from the game server cannot be submitted! Please use the link below to add your attachments.",
    "suggestSuccess": "Your suggestion has been sent! Please provide any screenshots or more information here:\n{{url}}",
    "timeNoDuration": "How long it should be? You forgot to state the duration.",
    "timeInvalidFormat": "Invalid time format!",
    "timeSet": "Setting the time for {{time}}",
    "timeIsUp": "Time is up! {{ping}}",
    "colorInvalid": "{{color}} is not a valid color!",
    "specialRoleMissing": "I am unable to find a special role assigned to you! If you have one, report this using `+bug`.",
    "colorNotSpecified": "Please specify a color!",
    "colorChanged": "Done! Your special role color has been changed!",
    "nameInvalid": "That name is invalid!",
    "nameSuccess": "Done! Your special role's name has been changed to {{name}}.",
    "profileNeedToBuy": "You need to buy the profile command in order to use it!",
    "profileLocked": "This player does not have their profile unlocked from the shop!",
    "profile": "Profile",
    "inventory": "Inventory",
    "shopTitle": "Wolvesville Simulation Shop",
    "shopFooter": "Use `+buy <color> role` to purchase a color.",
    "page": "Page",
    "availableColors": "Available Colors",
    "settingsHeader": "Customize your settings below!"
}